    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <div class="row-fluid">
            <div class="span2">
              
            </div>
            <div class="span8 text-warning">
              <a href="#" class="text-success" data-toggle="dropdown"><h4>成长阅读<b class="caret"></b></h4></a>
                <ul class="dropdown-menu" id="swatch-menu">
                  <li><a href="default"><i class="icon-envelope"></i>shaopu@</a></li>
                  <li><a href="default"><i class="icon-comment"></i>@小顶</a></li>
                </ul>
            </div>
            <div class="span2">
              <a href="#" class="btn pull-right" data-toggle="dropdown"><i class="icon-home"></i></a>
                <ul class="dropdown-menu pull-right" id="swatch-menu">
                  <li><a href="#myModal" role="button" data-toggle="modal">我是谁？</a></li>
                  <li><a href="default"><i class="icon-envelope"></i>shaopu@</a></li>
                  <li><a href="default"><i class="icon-comment"></i>@小顶</a></li>
                </ul>
            </div>
          </div>


        </div>
      </div>
    </div>