<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><?php echo $pagetitle; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="<?php echo $this->_uri_dir; ?>css/bootstrap<?php if($__visitor['h5mTheme']['theme']){echo '-'.$__visitor['h5mTheme']['theme'];} ?>.min.css" rel="stylesheet">
    <link href="<?php echo $this->_uri_dir; ?>css/bootstrap-responsive.css" rel="stylesheet">

    <link href="<?php echo $this->_uri_dir; ?>css/code.css" rel="stylesheet">
    <link href="<?php echo $this->_uri_dir; ?>css/h5mob.css" rel="stylesheet">
  </head>

  <body>