    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <div style="margin-left: 20px;margin-right: 20px;">
              <h4>
              <a href="#" class="text-success" data-toggle="dropdown" style="text-align: center;">成长阅读<b class="caret"></b></a>
              <a href="#" class="btn btn-mini pull-right" style="margin-top: 0px" data-toggle="dropdown"><i class="icon-home"></i></a>
                <ul class="dropdown-menu pull-right" id="swatch-menu">
                  <li><a href="#myModal" role="button" data-toggle="modal">我是谁？</a></li>
                  <li><a href="default"><i class="icon-envelope"></i>shaopu@</a></li>
                  <li><a href="default"><i class="icon-comment"></i>@小顶</a></li>
                </ul>
              </h4>
          </div>
        </div>
      </div>
    </div>