    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <div style="margin-left: 20px;margin-right: 20px;">
              <h4>
              <a href="#">成长阅读</b></a>
              <a href="#" class="btn btn-small pull-right btn-success" style="margin-top: 0px" data-toggle="dropdown"><i class="icon-home"></i></a>
                <ul class="dropdown-menu pull-right" id="swatch-menu">
                  <li><a href="./wrh5m_settingPerson.php"><i class="icon-user"></i>个人设置</a></li>
                  <li><a href="default"><i class="icon-book"></i>已读文章</a></li>
                  <li><a href="default"><i class="icon-comment"></i>@小顶</a></li>
                </ul>
              </h4>
          </div>
        </div>
      </div>
    </div>