<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><php echo $pagetitle; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="<?php echo $this->_uri_dir; ?>css/bootstrap.min.css" rel="stylesheet">
    <style>
      body {
        padding-top: 40px;
        padding-bottom: 40px;
      }
    </style>
    <link href="<?php echo $this->_uri_dir; ?>css/code.css" rel="stylesheet">
  </head>

  <body>