    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <div style="margin-left: 20px;margin-right: 20px;">
              <h4>
              <a href="#" class="text-success">设置</b></a>
              <a href="./wrh5m_suggestArticle.php" class="btn btn-mini pull-right" style="margin-top: 0px">返回阅读</a>
          </div>
        </div>
      </div>
    </div>