    <?php echo $scope; ?>
    <script src="<?php echo $this->_uri_dir; ?>js/jquery.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-transition.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-alert.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-modal.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-dropdown.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-scrollspy.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-tab.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-tooltip.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-popover.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-button.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-collapse.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-carousel.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/bootstrap-typeahead.js"></script>
    <script src="<?php echo $this->_uri_dir; ?>js/prettify.js"></script>
  </body>
</html>