<?php include($this->_tpl_dir.'/_tpl_htmlHeader.phtml'); ?>

<?php include($this->_tpl_dir.'/_tpl_navArticlelist.phtml'); ?>

    <div class="container">
      <table class="table table-striped">
        <tbody>
          <tr>
            <td>
              <h3>这是标题啊啊</h3>
              <div class="row-fluid">
                <div class="span4"> 35分钟前 来自 <a href="#">虎嗅</a></div>
                <div class="span4"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <h3>这是标题啊啊</h3>
              <div class="row-fluid">
                <div class="span4"> 35分钟前 来自 <a href="#">虎嗅</a></div>
                <div class="span4"></div>
              </div>
            </td>
          </tr><tr>
            <td>
              <h3>这是标题啊啊</h3>
              <div class="row-fluid">
                <div class="span4"> 35分钟前 来自 <a href="#">虎嗅</a></div>
                <div class="span4"></div>
              </div>
            </td>
          </tr><tr>
            <td>
              <h3>这是标题啊啊</h3>
              <div class="row-fluid">
                <div class="span4"> 35分钟前 来自 <a href="#">虎嗅</a></div>
                <div class="span4"></div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>

    </div>

<?php include($this->_tpl_dir.'/_tpl_htmlFooter.phtml'); ?>