<?php include($this->_tpl_dir.'/_tpl_htmlHeader.phtml'); ?>

<?php include($this->_tpl_dir.'/_tpl_navSetting.phtml'); ?>


    <div class="container-fluid" style="margin-top: 50px;">
      <?php include($this->_tpl_dir.'/_tpl_settingNav.phtml'); ?>
      
      <h4>
        当前帐号:<a href=""><?php echo $__visitor['nick']; ?></a>
		  </h4>	
	    
      <h4>成长情况</h4>
      <div style="padding-left: 20px">
      	职业:<?php echo $jobInfo['name']; ?><br/>
      	级别:<?php echo $levelInfo[$__visitor['job']['level']]['name']; ?><br/>
      </div>
      <h4>其他关注</h4>
      <div style="padding-left: 20px">
        <textarea class="input-large" placeholder="标签以空格分隔噢" id="iptAttendTag"><?php echo Tool_string::esc_edit_html(implode(' ',$__visitor['userJob']['attend_tag'])) ?></textarea>
        <a href="javascript:;" class="btn btn-mini pull-right" id="saveAttendTag">保存修改</a><span class="text-success pull-right" style="margin-right: 20px" id="msgAttend"></span>
      </div>
    </div>

<?php include($this->_tpl_dir.'/_tpl_htmlFooter.phtml'); ?>
<script type="text/javascript">
  $('#saveAttendTag').click(function(){

    $.post(
      'api/wr_setAttendTag.php',
      {tags:$('#iptAttendTag').val()},
      function(){
        $('#msgAttend').html('保存成功');
        setTimeout(function(){
          $('#msgAttend').html('');
        } , 1000);
      }
    );
    
  });
</script>