<?php include($this->_tpl_dir.'/_tpl_htmlHeader.phtml'); ?>

<?php include($this->_tpl_dir.'/_tpl_navArticlelist.phtml'); ?>


    <div class="container-fluid" style="margin-top: 40px;margin-left: -20px;margin-right:-20px ">
      <table class="table table-striped">
        <tbody>
          <?php foreach ($articleList as $key => $value) { ?>
          <tr>
            <td class="artLsType_<?php echo $value['suggestType'] ?>">
              <h3><a <?php if($value['readed']){ ?>class="muted"<?php } ?> href="wrh5m_articleShow.php?aid=<?php echo $value['id']; ?>" style="word-break: normal"><?php echo str_replace('&nbsp;' , ' ' , Tool_string::un_html($value['title'])); ?></a></h3>
              <div class="row-fluid">
                <div class="span4"><?php echo ml_tool_standardShow::time($value['pub_time']); ?> 来自 <a href="http://<?php echo $value['site_info']['domain'] ?>" target="_blank"><?php echo Tool_string::un_html($value['site_info']['site_name']) ?></a></div>
              </div>
            </td>
          </tr>
          <?php } ?>
          
        </tbody>
      </table>

    </div>
<?php echo memory_get_peak_usage()/1024/1024;  ?>
<?php include($this->_tpl_dir.'/_tpl_htmlFooter.phtml'); ?>