<?php include($this->_tpl_dir.'/_tpl_htmlHeader.phtml'); ?>

<?php include($this->_tpl_dir.'/_tpl_navArticleshow.phtml'); ?>


    <div class="container-fluid" style="margin-top: 40px;">
      <h3><?php echo Tool_string::un_html($articleInfo['title']); ?></h3>
      
        <?php echo ml_tool_standardShow::time($articleInfo['pub_time']); ?>
        来自 <a href="http://<?php echo $sourceInfo['domain']; ?>"><?php echo Tool_string::un_html($sourceInfo['site_name']); ?></a>
        <small><a href="<?php echo $articleInfo['link']; ?>" target="_blank">原文</a></small><br/>
        标签 <?php foreach ($articleInfo['tags'] as $key => $value) {?>
          <a href=""><?php echo Tool_string::un_html($value); ?></a>
        <?php } ?>
      
      <hr>
      <div<?php if($__visitor['h5mTheme']['data']['font-size']){?> style="font-size: <?php echo $__visitor['h5mTheme']['data']['font-size'] ?>px"<?php } ?>>
        <?php 

          echo ml_tool_standardShow::no_html( ml_tool_contentFormater_baseBySrc::outputFormatContent($sourceInfo['codeSign'] , $articleInfo['content'])); 
          ?>
      </div>

      <div class="btn-group">
        <button class="btn btn-large"><i class="icon-star"></i></button>
        <button class="btn btn-large"><i class="icon-share"></i></button>
        <button class="btn btn-large"><i class="icon-comment"></i></button>
      </div>
    </div>

<?php include($this->_tpl_dir.'/_tpl_htmlFooter.phtml'); ?>